/**
 * divvi protocol rewards integration. season 0 may 15th-july 31st 2025
 */

// generated by calling getDataSuffix({consumer: '0x66582D24FEaD72555adaC681Cc621caCbB208324',providers: ['0x0423189886d7966f0dd7e7d256898daeee625dca']})
export const GD_DATASUFFIX =
  "6decb85d0000000000000000000000000066582d24fead72555adac681cc621cacbb208324000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000423189886d7966f0dd7e7d256898daeee625dca00000089"

const DIVVI_MARKED_KEY = (chainId: number, wallet: string) =>
  `goodDollarDivviMarked_${chainId}_${wallet}`

export const isDivviMarked = (chainId: number, wallet: string): boolean => {
  if (typeof localStorage === "undefined") {
    return true
  }
  return JSON.parse(
    localStorage.getItem(DIVVI_MARKED_KEY(chainId, wallet)) || "false",
  )
}

export const setDivviMarked = (chainId: number, wallet: string) => {
  if (typeof localStorage === "undefined") {
    return
  }
  localStorage.setItem(DIVVI_MARKED_KEY(chainId, wallet), "true")
}
/**
 * Posts an attribution event to the tracking API
 *
 * @param params - The parameters for the attribution event
 * @param params.txHash - The transaction hash
 * @param params.chainId - The chain ID
 * @param params.baseUrl - The base URL for the API endpoint (optional)
 * @returns A promise that resolves to the response from the API
 * @throws {Error} Client error (4xx) - When the request fails due to client-side issues
 * @throws {Error} Server error (5xx) - When the request fails due to server-side issues, client should retry the request
 */
export async function submitReferral({
  txHash,
  chainId,
  baseUrl = "https://api.divvi.xyz/submitReferral",
}: {
  txHash: string
  chainId: number
  baseUrl?: string
}): Promise<Response> {
  const response = await fetch(baseUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      txHash,
      chainId,
    }),
  })

  if (!response.ok) {
    // Handle 4xx client errors
    if (response.status >= 400 && response.status < 500) {
      const errorResponse = await response.text()
      throw new Error(
        `Client error: ${response.status} ${response.statusText} ${errorResponse}`,
      )
    }
    // Handle all other errors (5xx server errors, etc.)
    throw new Error(
      `Server error: Failed to submit referral event: ${response.statusText}. Client should retry the request.`,
    )
  }

  return response
}
